# Generated by Django 5.2.7 on 2025-10-16 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fragancia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_fragancia', models.CharField(max_length=155)),
                ('precio_fragancia', models.PositiveIntegerField()),
                ('stock_fragancia', models.PositiveIntegerField()),
                ('descripcion_fragancia', models.TextField()),
                ('imagen_fragancia', models.CharField(max_length=555)),
            ],
        ),
        migrations.CreateModel(
            name='Polera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_polera', models.CharField(max_length=155)),
                ('precio_polera', models.PositiveIntegerField()),
                ('stock_polera', models.PositiveIntegerField()),
                ('descripcion_polera', models.TextField()),
                ('imagen_polera', models.CharField(max_length=555)),
            ],
        ),
    ]
