# Generated by Django 5.2.7 on 2025-10-16 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fragancia',
            name='tipo_fragancia',
            field=models.CharField(default='', max_length=55),
        ),
    ]
