# Generated by Django 5.2.7 on 2025-10-17 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miApp', '0002_fragancia_tipo_fragancia'),
    ]

    operations = [
        migrations.AddField(
            model_name='fragancia',
            name='link_fragancia',
            field=models.CharField(default='', max_length=555),
        ),
    ]
